import { Effect } from '../types/effect.types'
import blurFrag from '../shaders/effects/blur.frag?raw'
import pixelateFrag from '../shaders/effects/pixelate.frag?raw'
import rgbSplitFrag from '../shaders/effects/rgbSplit.frag?raw'
import glitchFrag from '../shaders/effects/glitch.frag?raw'
import swirlFrag from '../shaders/effects/swirl.frag?raw'
import kaleidoscopeFrag from '../shaders/effects/kaleidoscope.frag?raw'
import mirrorFrag from '../shaders/effects/mirror.frag?raw'
import waveFrag from '../shaders/effects/wave.frag?raw'
import chromakeyFrag from '../shaders/effects/chromakey.frag?raw'
import vignetteFrag from '../shaders/effects/vignette.frag?raw'
import colorgradeFrag from '../shaders/effects/colorgrade.frag?raw'
import pixelsortFrag from '../shaders/effects/pixelsort.frag?raw'
import noiseFrag from '../shaders/effects/noise.frag?raw'
import voronoiFrag from '../shaders/effects/voronoi.frag?raw'
import edgeFrag from '../shaders/effects/edge.frag?raw'
import displacementFrag from '../shaders/effects/displacement.frag?raw'
import polarFrag from '../shaders/effects/polar.frag?raw'
import posterizeFrag from '../shaders/effects/posterize.frag?raw'
import halftoneFrag from '../shaders/effects/halftone.frag?raw'
import audioreactiveFrag from '../shaders/effects/audioreactive.frag?raw'
import audiowaveFrag from '../shaders/effects/audiowave.frag?raw'
import vectordisplaceFrag from '../shaders/effects/vectordisplace.frag?raw'
import flowfieldFrag from '../shaders/effects/flowfield.frag?raw'
import psychedelicFrag from '../shaders/effects/psychedelic.frag?raw'
import fractalzoomFrag from '../shaders/effects/fractalzoom.frag?raw'
import mandelbrotFrag from '../shaders/effects/mandelbrot.frag?raw'
import juliaFrag from '../shaders/effects/julia.frag?raw'
import feedbackFrag from '../shaders/effects/feedback.frag?raw'
import mirrortunnelFrag from '../shaders/effects/mirrortunnel.frag?raw'
import datamoshFrag from '../shaders/effects/datamosh.frag?raw'
import bloomFrag from '../shaders/effects/bloom.frag?raw'

export const availableEffects: Effect[] = [
  {
    id: 'blur',
    name: 'Blur',
    description: 'Multi-mode blur with Gaussian, Box, Kawase, Directional, Radial, Tilt-shift',
    category: 'simple',
    fragmentShader: blurFrag,
    parameters: [
      {
        name: 'uMode',
        label: 'Mode',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 5,
        step: 1,
      },
      {
        name: 'uRadius',
        label: 'Radius',
        type: 'float',
        defaultValue: 5.0,
        min: 0,
        max: 20,
        step: 0.5,
      },
      {
        name: 'uDirection',
        label: 'Direction',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.1,
      },
      {
        name: 'uCenterX',
        label: 'Center X',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uCenterY',
        label: 'Center Y',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uIterations',
        label: 'Iterations',
        type: 'float',
        defaultValue: 8,
        min: 1,
        max: 32,
        step: 1,
      },
      {
        name: 'uLumaPreserve',
        label: 'Luma Preserve',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uEdgeBehavior',
        label: 'Edge Behavior',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
    ],
    enabled: true,
  },
  {
    id: 'pixelate',
    name: 'Pixelate',
    description: 'Advanced pixelation with cell shapes, color sampling, and jitter',
    category: 'simple',
    fragmentShader: pixelateFrag,
    parameters: [
      {
        name: 'uCellSizeX',
        label: 'Cell Width',
        type: 'float',
        defaultValue: 10,
        min: 2,
        max: 50,
        step: 1,
      },
      {
        name: 'uCellSizeY',
        label: 'Cell Height',
        type: 'float',
        defaultValue: 10,
        min: 2,
        max: 50,
        step: 1,
      },
      {
        name: 'uShape',
        label: 'Shape',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
      {
        name: 'uAlignment',
        label: 'Alignment',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uColorSampling',
        label: 'Color Sampling',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uJitter',
        label: 'Jitter',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'rgbSplit',
    name: 'RGB Split',
    description: 'Intelligent RGB split with luma-based offset and temporal jitter',
    category: 'simple',
    fragmentShader: rgbSplitFrag,
    parameters: [
      {
        name: 'uOffsetMagnitude',
        label: 'Offset',
        type: 'float',
        defaultValue: 2,
        min: 0,
        max: 10,
        step: 0.5,
      },
      {
        name: 'uDirection',
        label: 'Direction',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.1,
      },
      {
        name: 'uChannelR',
        label: 'Enable R',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uChannelG',
        label: 'Enable G',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uChannelB',
        label: 'Enable B',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uLumaInfluence',
        label: 'Luma Influence',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 0.1,
      },
      {
        name: 'uTemporalJitter',
        label: 'Temporal Jitter',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'glitch',
    name: 'Glitch',
    description: 'Modular glitch with line shift, block displacement, channel desync, time slice, compression artifacts',
    category: 'simple',
    fragmentShader: glitchFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uFrequency',
        label: 'Frequency',
        type: 'float',
        defaultValue: 5,
        min: 0,
        max: 20,
        step: 0.5,
      },
      {
        name: 'uSeed',
        label: 'Seed',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        name: 'uLineShift',
        label: 'Line Shift',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uBlockDisplace',
        label: 'Block Displace',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uChannelDesync',
        label: 'Channel Desync',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uTimeSlice',
        label: 'Time Slice',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uCompressionArtifacts',
        label: 'Compression',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uHorizontalBias',
        label: 'Horizontal Bias',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  {
    id: 'swirl',
    name: 'Swirl',
    description: 'Spiral distortion from center',
    category: 'geometric',
    fragmentShader: swirlFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 2,
        min: 0,
        max: 10,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  {
    id: 'kaleidoscope',
    name: 'Kaleidoscope',
    description: 'Radial symmetry mirroring',
    category: 'geometric',
    fragmentShader: kaleidoscopeFrag,
    parameters: [
      {
        name: 'uSegments',
        label: 'Segments',
        type: 'float',
        defaultValue: 6,
        min: 2,
        max: 32,
        step: 1,
      },
      {
        name: 'uRotation',
        label: 'Rotation',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.01,
      },
      {
        name: 'uMode',
        label: 'Mode',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uEdgeSoftness',
        label: 'Edge Softness',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        name: 'uCenterX',
        label: 'Center X',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uCenterY',
        label: 'Center Y',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uZoom',
        label: 'Zoom',
        type: 'float',
        defaultValue: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  {
    id: 'mirror',
    name: 'Mirror',
    description: 'Flip and mirror axes',
    category: 'geometric',
    fragmentShader: mirrorFrag,
    parameters: [
      {
        name: 'uMirrorCount',
        label: 'Mirror Count',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 4,
        step: 1,
      },
      {
        name: 'uAxisAngle',
        label: 'Axis Angle',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.01,
      },
      {
        name: 'uOffsetX',
        label: 'Offset X',
        type: 'float',
        defaultValue: 0,
        min: -0.5,
        max: 0.5,
        step: 0.01,
      },
      {
        name: 'uOffsetY',
        label: 'Offset Y',
        type: 'float',
        defaultValue: 0,
        min: -0.5,
        max: 0.5,
        step: 0.01,
      },
      {
        name: 'uBlendSeams',
        label: 'Blend Seams',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
    enabled: true,
  },
  {
    id: 'wave',
    name: 'Wave',
    description: 'Sine wave distortion',
    category: 'geometric',
    fragmentShader: waveFrag,
    parameters: [
      {
        name: 'uAmplitude',
        label: 'Amplitude',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        name: 'uFrequency',
        label: 'Frequency',
        type: 'float',
        defaultValue: 5,
        min: 1,
        max: 20,
        step: 0.5,
      },
    ],
    enabled: true,
  },
  {
    id: 'vignette',
    name: 'Vignette',
    description: 'Darken edges of frame',
    category: 'color',
    fragmentShader: vignetteFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uRadius',
        label: 'Radius',
        type: 'float',
        defaultValue: 0.75,
        min: 0,
        max: 2,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'colorgrade',
    name: 'Color Grade',
    description: 'Adjust brightness, contrast, saturation, hue',
    category: 'color',
    fragmentShader: colorgradeFrag,
    parameters: [
      {
        name: 'uBrightness',
        label: 'Brightness',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uContrast',
        label: 'Contrast',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uSaturation',
        label: 'Saturation',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uHue',
        label: 'Hue',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'pixelsort',
    name: 'Pixel Sort',
    description: 'Sort pixels by brightness',
    category: 'signal',
    fragmentShader: pixelsortFrag,
    parameters: [
      {
        name: 'uThreshold',
        label: 'Threshold',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 3,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  {
    id: 'noise',
    name: 'Noise Distortion',
    description: 'Multi-type noise distortion with Simplex, Perlin, Curl, and Value noise',
    category: 'generative',
    fragmentShader: noiseFrag,
    parameters: [
      {
        name: 'uNoiseType',
        label: 'Type',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 3,
        step: 1,
      },
      {
        name: 'uScale',
        label: 'Scale',
        type: 'float',
        defaultValue: 1,
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        name: 'uTimeSpeed',
        label: 'Time Speed',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        name: 'uAxisLock',
        label: 'Axis Lock',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
      {
        name: 'uSeed',
        label: 'Seed',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 100,
        step: 1,
      },
    ],
    enabled: true,
  },
  {
    id: 'voronoi',
    name: 'Voronoi',
    description: 'Cellular pattern overlay',
    category: 'generative',
    fragmentShader: voronoiFrag,
    parameters: [
      {
        name: 'uCells',
        label: 'Cells',
        type: 'float',
        defaultValue: 10,
        min: 2,
        max: 50,
        step: 1,
      },
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'edge',
    name: 'Edge Detection',
    description: 'Sobel edge detection',
    category: 'signal',
    fragmentShader: edgeFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uThickness',
        label: 'Thickness',
        type: 'float',
        defaultValue: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  {
    id: 'displacement',
    name: 'Displacement',
    description: 'Noise-based displacement mapping',
    category: 'generative',
    fragmentShader: displacementFrag,
    parameters: [
      {
        name: 'uMapSource',
        label: 'Map Source',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 4,
        step: 1,
      },
      {
        name: 'uIntensityX',
        label: 'Intensity X',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uIntensityY',
        label: 'Intensity Y',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uScale',
        label: 'Scale',
        type: 'float',
        defaultValue: 5,
        min: 0.5,
        max: 20,
        step: 0.5,
      },
      {
        name: 'uTimeSpeed',
        label: 'Time Speed',
        type: 'float',
        defaultValue: 0.1,
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uEdgeBehavior',
        label: 'Edge Behavior',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
      {
        name: 'uSmoothness',
        label: 'Smoothness',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        name: 'uSeed',
        label: 'Seed',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 100,
        step: 1,
      },
    ],
    enabled: true,
  },
  {
    id: 'polar',
    name: 'Polar Coordinates',
    description: 'Transform to polar coordinate space',
    category: 'geometric',
    fragmentShader: polarFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'posterize',
    name: 'Posterize',
    description: 'Advanced posterization with per-channel control and dithering',
    category: 'color',
    fragmentShader: posterizeFrag,
    parameters: [
      {
        name: 'uLevelsR',
        label: 'Levels R',
        type: 'float',
        defaultValue: 8,
        min: 2,
        max: 32,
        step: 1,
      },
      {
        name: 'uLevelsG',
        label: 'Levels G',
        type: 'float',
        defaultValue: 8,
        min: 2,
        max: 32,
        step: 1,
      },
      {
        name: 'uLevelsB',
        label: 'Levels B',
        type: 'float',
        defaultValue: 8,
        min: 2,
        max: 32,
        step: 1,
      },
      {
        name: 'uMode',
        label: 'Mode',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uDitheringType',
        label: 'Dither Type',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
      {
        name: 'uDitherIntensity',
        label: 'Dither Intensity',
        type: 'float',
        defaultValue: 0.1,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'halftone',
    name: 'Halftone',
    description: 'CMYK halftone with dot shapes, angles, and ink spread',
    category: 'signal',
    fragmentShader: halftoneFrag,
    parameters: [
      {
        name: 'uDotShape',
        label: 'Dot Shape',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
      {
        name: 'uFrequency',
        label: 'Frequency',
        type: 'float',
        defaultValue: 10,
        min: 2,
        max: 30,
        step: 1,
      },
      {
        name: 'uAngleC',
        label: 'Angle C',
        type: 'float',
        defaultValue: 0.262,
        min: 0,
        max: 6.28,
        step: 0.1,
      },
      {
        name: 'uAngleM',
        label: 'Angle M',
        type: 'float',
        defaultValue: 1.309,
        min: 0,
        max: 6.28,
        step: 0.1,
      },
      {
        name: 'uAngleY',
        label: 'Angle Y',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.1,
      },
      {
        name: 'uAngleK',
        label: 'Angle K',
        type: 'float',
        defaultValue: 0.785,
        min: 0,
        max: 6.28,
        step: 0.1,
      },
      {
        name: 'uInkSpread',
        label: 'Ink Spread',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uThreshold',
        label: 'Threshold',
        type: 'float',
        defaultValue: 1,
        min: 0.5,
        max: 2,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  // Audio-Reactive Effects
  {
    id: 'audioreactive',
    name: 'Audio Reactive',
    description: 'Responds to audio frequencies (bass/mid/treble)',
    category: 'audio',
    fragmentShader: audioreactiveFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 3,
        step: 0.1,
      },
      {
        name: 'uBassLevel',
        label: 'Bass Level',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uMidLevel',
        label: 'Mid Level',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uTrebleLevel',
        label: 'Treble Level',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'audiowave',
    name: 'Audio Wave',
    description: 'Waveform visualization effects',
    category: 'audio',
    fragmentShader: audiowaveFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 3,
        step: 0.1,
      },
      {
        name: 'uFrequency',
        label: 'Frequency',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  // Displacement Effects
  {
    id: 'vectordisplace',
    name: 'Vector Displacement',
    description: 'Noise-driven vector field displacement',
    category: 'displacement',
    fragmentShader: vectordisplaceFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  {
    id: 'flowfield',
    name: 'Flow Field',
    description: 'Flowing displacement patterns',
    category: 'displacement',
    fragmentShader: flowfieldFrag,
    parameters: [
      {
        name: 'uFieldType',
        label: 'Field Type',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 4,
        step: 1,
      },
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uViscosity',
        label: 'Viscosity',
        type: 'float',
        defaultValue: 0.3,
        min: 0,
        max: 0.95,
        step: 0.05,
      },
      {
        name: 'uIterations',
        label: 'Iterations',
        type: 'float',
        defaultValue: 5,
        min: 1,
        max: 20,
        step: 1,
      },
      {
        name: 'uScale',
        label: 'Scale',
        type: 'float',
        defaultValue: 3,
        min: 0.5,
        max: 20,
        step: 0.5,
      },
      {
        name: 'uSpeed',
        label: 'Speed',
        type: 'float',
        defaultValue: 0.1,
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uAttractorCount',
        label: 'Attractor Enable',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 1,
      },
      {
        name: 'uAttractorX1',
        label: 'Attractor X',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uAttractorY1',
        label: 'Attractor Y',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uAttractorStrength1',
        label: 'Attractor Strength',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        name: 'uSeed',
        label: 'Seed',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 100,
        step: 1,
      },
    ],
    enabled: true,
  },
  // Psychedelic Effects
  {
    id: 'psychedelic',
    name: 'Psychedelic',
    description: 'Spiraling kaleidoscopic distortion',
    category: 'psychedelic',
    fragmentShader: psychedelicFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 2,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  {
    id: 'fractalzoom',
    name: 'Fractal Zoom',
    description: 'Infinite zoom fractal effect',
    category: 'psychedelic',
    fragmentShader: fractalzoomFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 2,
        step: 0.1,
      },
    ],
    enabled: true,
  },
  // Mathematical Fractals
  {
    id: 'mandelbrot',
    name: 'Mandelbrot',
    description: 'Video mapped into Mandelbrot fractal space',
    category: 'mathematical',
    fragmentShader: mandelbrotFrag,
    parameters: [
      {
        name: 'uIterations',
        label: 'Iterations',
        type: 'float',
        defaultValue: 50,
        min: 10,
        max: 200,
        step: 5,
      },
      {
        name: 'uZoom',
        label: 'Zoom',
        type: 'float',
        defaultValue: 1,
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uPanX',
        label: 'Pan X',
        type: 'float',
        defaultValue: -0.5,
        min: -2,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uPanY',
        label: 'Pan Y',
        type: 'float',
        defaultValue: 0,
        min: -2,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uColorMode',
        label: 'Color Mode',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
      {
        name: 'uVideoInfluence',
        label: 'Video Influence',
        type: 'float',
        defaultValue: 0.8,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        name: 'uRotation',
        label: 'Rotation',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  {
    id: 'julia',
    name: 'Julia Set',
    description: 'Video mapped into Julia fractal space',
    category: 'mathematical',
    fragmentShader: juliaFrag,
    parameters: [
      {
        name: 'uIterations',
        label: 'Iterations',
        type: 'float',
        defaultValue: 50,
        min: 10,
        max: 200,
        step: 5,
      },
      {
        name: 'uZoom',
        label: 'Zoom',
        type: 'float',
        defaultValue: 1,
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uPanX',
        label: 'Pan X',
        type: 'float',
        defaultValue: 0,
        min: -2,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uPanY',
        label: 'Pan Y',
        type: 'float',
        defaultValue: 0,
        min: -2,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uConstantX',
        label: 'Constant X',
        type: 'float',
        defaultValue: -0.7,
        min: -2,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uConstantY',
        label: 'Constant Y',
        type: 'float',
        defaultValue: 0.27,
        min: -2,
        max: 2,
        step: 0.01,
      },
      {
        name: 'uColorMode',
        label: 'Color Mode',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 2,
        step: 1,
      },
      {
        name: 'uVideoInfluence',
        label: 'Video Influence',
        type: 'float',
        defaultValue: 0.8,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        name: 'uRotation',
        label: 'Rotation',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  // Transform Feedback Effects
  {
    id: 'feedback',
    name: 'Feedback Loop',
    description: 'Recursive frame feedback with rotation and scale',
    category: 'feedback',
    fragmentShader: feedbackFrag,
    parameters: [
      {
        name: 'uFeedbackAmount',
        label: 'Feedback Amount',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uScale',
        label: 'Scale',
        type: 'float',
        defaultValue: 1.0,
        min: 0.9,
        max: 1.1,
        step: 0.001,
      },
      {
        name: 'uRotation',
        label: 'Rotation',
        type: 'float',
        defaultValue: 0,
        min: -10,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uOffsetX',
        label: 'Offset X',
        type: 'float',
        defaultValue: 0,
        min: -10,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uOffsetY',
        label: 'Offset Y',
        type: 'float',
        defaultValue: 0,
        min: -10,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uDecay',
        label: 'Decay',
        type: 'float',
        defaultValue: 0.98,
        min: 0.8,
        max: 1.0,
        step: 0.01,
      },
      {
        name: 'uBlendMode',
        label: 'Blend Mode',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 3,
        step: 1,
      },
      {
        name: 'uStabilization',
        label: 'Stabilization',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 1,
      },
    ],
    enabled: true,
  },
  {
    id: 'mirrortunnel',
    name: 'Mirror Tunnel',
    description: 'Infinite mirror tunnel effect',
    category: 'feedback',
    fragmentShader: mirrortunnelFrag,
    parameters: [
      {
        name: 'uDepthLayers',
        label: 'Depth Layers',
        type: 'float',
        defaultValue: 5,
        min: 1,
        max: 20,
        step: 1,
      },
      {
        name: 'uSegments',
        label: 'Segments',
        type: 'float',
        defaultValue: 6,
        min: 2,
        max: 32,
        step: 1,
      },
      {
        name: 'uSpeed',
        label: 'Speed',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        name: 'uTwist',
        label: 'Twist',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 10,
        step: 0.1,
      },
      {
        name: 'uScalePerLayer',
        label: 'Scale Per Layer',
        type: 'float',
        defaultValue: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
      },
      {
        name: 'uColorShift',
        label: 'Color Shift',
        type: 'float',
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        name: 'uCenterX',
        label: 'Center X',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uCenterY',
        label: 'Center Y',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  // Datamosh Engine
  {
    id: 'datamosh',
    name: 'Datamosh',
    description: 'Video compression glitches and artifacts',
    category: 'glitch',
    fragmentShader: datamoshFrag,
    parameters: [
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    enabled: true,
  },
  // Bloom / Glow Effect
  {
    id: 'bloom',
    name: 'Bloom / Glow',
    description: 'Luminous glow effect with threshold, radius, intensity, and quality controls',
    category: 'color',
    fragmentShader: bloomFrag,
    parameters: [
      {
        name: 'uThreshold',
        label: 'Threshold',
        type: 'float',
        defaultValue: 0.7,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: 'uRadius',
        label: 'Radius',
        type: 'float',
        defaultValue: 8,
        min: 1,
        max: 20,
        step: 0.5,
      },
      {
        name: 'uIntensity',
        label: 'Intensity',
        type: 'float',
        defaultValue: 1,
        min: 0,
        max: 3,
        step: 0.1,
      },
      {
        name: 'uQuality',
        label: 'Quality',
        type: 'float',
        defaultValue: 3,
        min: 1,
        max: 5,
        step: 1,
      },
    ],
    enabled: true,
  },
]
